### ISSUE TITLE
enhancement: more configurable ibm_container_bind_service it needs to support k8s and pvc/cos

### ISSUE THREAD

**Issue by powellquiring** [IBM-Cloud/terraform-provider-ibm#2167]
- Expected: A way to create a kuberrnetes secret resource with the required parameters from parameters and an ibm_resource_instance
- Actual: not possible

Proposal:

The ibm_container_bind_service` enhancment:

```
resource "ibm_container_bind_service" "bind_objectstorage" {
  ...
  key            = "${var.environment_name}-cos-hmac-secret"
  type           = "ibm/ibmc-s3fs"
  mapping        = ?
}
```

- type String Type string like `ibm/ibmc-s3fs` needed for the PVC use case below
- mapping ? mapping from key to secret.  I'm not sure how to do this.  Take a look at the example below for a use case that needs to be expressed.

Use Case to express:

The k8s service supports a There is Persistent Volume, pv, storage class `ibmc-s3fs-standard-regional`.  A Persistent Volume Claim, pvc, resource can be created that ties ibmc-s3fs-standard-regional to a COS instance and bucket.  To create a directory backed by the bucket the pod mount a volume with the pvc.

Kubernetes deployment fragment with the volume for the pod included:

```
kind: Deployment
spec:
  selector:
    matchLabels:
      app: ikscos001nginx
  template:
    spec:
      - image: us.icr.io/ikscos001/nginx:latest
      containers:
        volumeMounts:
        - name: volname
          mountPath: /usr/share/nginx/html
      volumes:
      - name: volname
        persistentVolumeClaim:
          claimName: ikscos001nginxcosbucket

```

pvc fagment:

```
kind: PersistentVolumeClaim
metadata:
  annotations:
    ibm.io/auto-create-bucket: "true"
    ibm.io/secret-name: "cos-write-access"
spec:
  storageClassName: ibmc-s3fs-standard-regional
```

The cos-write-access kubernetes secret contains two keys.  The goal of this enhancement is to create this secret:

```
$ kc describe secret/cos-write-access
Type:  ibm/ibmc-s3fs
Data
====
access-key:  32 bytes
secret-key:  48 bytes
```

In the COS console ui they are part of a service credential configured with an advanced option { "HMAC": true }. In the cli the same object is called a service instance's service key:

```
$ ibmcloud resource service-key-create cos-write-access --instance-name objectstorage --parameters '{ "HMAC": true }' -g default
Credentials:
               apikey:                   YxYFD-CyadayadayadawEFfmm5kpqlyarO6WpiDzL1tQ
               cos_hmac_keys:
                                         access_key_id:       yadaaccessda405695dyadayadayadaf
                                         secret_access_key:   yadasecretdaa91e95b2e09401d5e23de8fyadayadayada3
```

Thee `access_key_id` and `secret_access_key` are the values needed in this command:

```
$ kubectl create secret generic cos-write-access --type=ibm/ibmc-s3fs --from-literal=access-key=yadaaccessda405695dyadayadayadaf --from-literal=secret-key=yadasecretdaa91e95b2e09401d5e23de8fyadayadayada3
```

It is not possible to make this secret key using terraform.  here is what I've tried:

```
# bind the cloud object storage service to the cluster
resource "ibm_container_bind_service" "bind_objectstorage" {
  cluster_name_id = ibm_container_vpc_cluster.cluster.id
  service_instance_id = ibm_resource_instance.objectstorage.guid
  namespace_id        = "default"
  resource_group_id   = data.ibm_resource_group.group.id
  role = "Writer"
}
```

This both creates the credential and creates the kubernetes secret.  But it is missing:
- parameter - can not specify '{ "HMAC": true }' in the cos service credentials
- type - can not specify kubrernetes secret: Type:  `ibm/ibmc-s3fs`
- keys - the kubrernetes secret keys: `access-key` and `secret-key` can not be created.

It is possible to explicitly create the service instance service key:

```
resource "ibm_resource_key" "objectstorage" {
  name                 = "${var.environment_name}-cos-hmac-secret"
  role                 = "Writer"
  resource_instance_id = ibm_resource_instance.objectstorage.id

  parameters = {
     HMAC: true
  }
}

resource "ibm_container_bind_service" "bind_objectstorage" {
  ...
  key                 = "${var.environment_name}-cos-hmac-secret"
}
```

This fixes the parameter problem but leaves these two:
- type - can not specify kubrernetes secret: Type:  `ibm/ibmc-s3fs`
- keys - the kubrernetes secret keys: `access-key` and `secret-key` can not be created.
