### ISSUE TITLE
How to use provision scripts outside resource creation block?

### ISSUE THREAD

**Issue by starlord-dixon** [IBM-Cloud/terraform-provider-ibm#230]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.7

provider.ibm (unversioned)

### Affected Resource(s)
Please list the resources as a list, for example:
ibm_compute_vm_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
```
# Create a virtual server
resource "ibm_compute_vm_instance" "virtual_server" {
  hostname           = "${var.vs_domain}"
  domain             = "${var.vs_domain}"
  os_reference_code  = "${var.vs_os_reference_code}"
  datacenter         = "${var.vs_datacenter}"
  cores              = "${var.vs_cores}"
  memory             = "${var.vs_memory}"
  network_speed      = "${var.vs_network_speed}"
  disks              = "${var.vs_disks}"
  hourly_billing     = "${var.vs_hourly_billing}"
  notes              = "${var.vs_notes}"
  user_metadata      = "{\"Hello from Terraform\":\"This is a Terraform test\"}"
  ssh_key_ids        = ["${local.ssh_key_id}"]
  private_network_only = "${var.vs_private_network_only}"
 
  
  # Define the SSH keys used to make connection to host
  connection {
    user = "root"
    type = "ssh"
    private_key = "${file("${var.ssh_key["private_key_path"]}")}"
  }
  
  
  provisioner "file" {
    source      =shell_scripts/install.sh"
    destination = "/tmp/install.sh"
  }

  # Execute commands on the host using the 'remote-exec' provisioner
  provisioner "remote-exec" {
    inline = [
      "chmod +x /tmp/install.sh",
      "sh /tmp/install.sh",
	  "rm -f /tmp/install.sh"
    ]
  }
  ```
 
}

### Questions
Currently if provision script script fails. the resource is marked has tainted.
Is there any way where we can separate the provision scripts from the resource creation?
Can i use null_resource to connect to the existing cluster and provision the scripts?

**Comment by hkantare** [comment]
Yes you can use null resource to execute scripts.
`https://www.terraform.io/docs/provisioners/null_resource.html`

**Comment by jkwong888** [comment]
i have a similar use case, and actually you should leverage `user_metadata`/cloud-init for these types of things where you want something to run inside the machine asynchronously after the VM is created.  e.g.:

```
#cloud-config
users:
  - default
  - name: myuser
    groups: [ wheel ]
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    shell: /bin/bash
    ssh-authorized-keys:
      - ${tls_private_key.mykey.public_key_openssh}
write_files:
  - path: /opt/scripts/bootstrap.sh
    permissions: '0755'
    encoding: b64
    content: ${base64encode(file("${path.module}/scripts/bootstrap.sh"))}
runcmd:
  - /opt/scripts/bootstrap.sh
EOF
```

see the cloud-init docs for what you can do:
http://cloudinit.readthedocs.io/en/latest/
