### ISSUE TITLE
create new data source for fetching an iam service policy

### ISSUE THREAD

**Issue by VaishnaviGopal** [IBM-Cloud/terraform-provider-ibm#2377]
Creation of new data source for fetching an iam service policy is required to fix a bug related to the creation of a policy using [ansible collection](https://github.com/IBM-Cloud/ansible-collection-ibm)

**Comment by mbwhite** [comment]
Hello - for reference what I'm trying to do is replicate the command 
```
 ibmcloud iam service-policy-create {{ iam_service_id }} --roles Reader --service-name container-registry
```
with an Ansible task as follows
```
    - name: Create Service Policy
      ibm_iam_service_policy:
        roles: 
         - Reader
        state: "available"
        region: "{{ region }}"
        iam_service_id: "{{ iam_service_id }}"  
        ibmcloud_api_key: "{{ cloud_api_key }}"
        resources:
          - service: "container-registry"
      register: policy
```
This ansible task has no effect, and doesn't set the policy to access the Container Registry
