### ISSUE TITLE
data "ibm_container_cluster_config" results in intermittent authentication as 'system:anonymous'

### ISSUE THREAD

**Issue by vburckhardt** [IBM-Cloud/terraform-provider-ibm#2811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
terraform -v
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/ibm-cloud/ibm v1.27.1
```

### Affected Resource(s)

data "ibm_container_cluster_config" 

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl

data "ibm_container_cluster_config" "cluster_config" {
  cluster_name_id = var.cluster_id
}

##############################################################################
# Config providers
##############################################################################

provider "ibm" {
  ibmcloud_api_key = var.ibmcloud_api_key
}

provider "helm" {
  kubernetes {
    host                   = data.ibm_container_cluster_config.cluster_config.host
    token                  = data.ibm_container_cluster_config.cluster_config.token
    cluster_ca_certificate = data.ibm_container_cluster_config.cluster_config.ca_certificate
  }
}

resource "helm_release" "service-mesh-operator" {
    ....
}

```

### Debug Output

```
TestOCPSMBasicExistingCluster/TestOCPSMBasicExistingCluster_1 2021-07-05T00:21:51+01:00 logger.go:66: │ Error: query: failed to query with labels: secrets is forbidden: User "system:anonymous" cannot list resource "secrets" in API group "" in the namespace "openshift-operators"
TestOCPSMBasicExistingCluster/TestOCPSMBasicExistingCluster_1 2021-07-05T00:21:51+01:00 logger.go:66: │ 
TestOCPSMBasicExistingCluster/TestOCPSMBasicExistingCluster_1 2021-07-05T00:21:51+01:00 logger.go:66: │   with module.service-mesh.helm_release.service-mesh-operator[0],
TestOCPSMBasicExistingCluster/TestOCPSMBasicExistingCluster_1 2021-07-05T00:21:51+01:00 logger.go:66: │   on ../../main.tf line 81, in resource "helm_release" "service-mesh-operator":
TestOCPSMBasicExistingCluster/TestOCPSMBasicExistingCluster_1 2021-07-05T00:21:51+01:00 logger.go:66: │   81: resource "helm_release" "service-mesh-operator" {
TestOCPSMBasicExistingCluster/TestOCPSMBasicExistingCluster_1 2021-07-05T00:21:51+01:00 logger.go:66: │ 
TestOCPSMBasicExistingCluster/TestOCPSMBasicExistingCluster_1 2021-07-05T00:21:51+01:00 logger.go:66: ╵
TestOCPSMBasicExistingCluster/TestOCPSMBasicExistingCluster_1 2021-07-05T00:21:51+01:00 retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1;
```

### Expected Behavior

Passed API Key is a personal API key of an admin on the IBM Cloud OpenShift cluster. User identify should always be of that user.

### Actual Behavior

Occasionally (~1 in 10 times) - user is authenticated as 'system:anonymous'.  Issues happens occasionally - typically re-running apply or destroy gets past the issue.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by vburckhardt** [comment]
Update: This is **consistently** reproducible using a Service ID API key as opposed to a Personal API Key (intermittent with personal api key). This also results in side affects which I believe have the same root cause - eg: helm provider returning "Error: unable to build kubernetes objects from release manifest: unknown"

I did some more digging locally - when the issue occurs, here is the content of the kube config that is set/downloaded by the provider. Notice there is no user, and no token set.

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://c100-e.au-syd.containers.cloud.ibm.com:30433
  name: sm-zqe5to-testsm-gp-6-ocp/c3gj1v5s005sa12n1sm0
- cluster:
    server: https://c100-e.au-syd.containers.cloud.ibm.com:30433
  name: c100-e-au-syd-containers-cloud-ibm-com:30433
contexts:
- context:
    cluster: sm-zqe5to-testsm-gp-6-ocp/c3gj1v5s005sa12n1sm0
    namespace: default
    user: ""
  name: sm-zqe5to-testsm-gp-6-ocp/c3gj1v5s005sa12n1sm0
- context:
    cluster: c100-e-au-syd-containers-cloud-ibm-com:30433
    namespace: default
    user: /c100-e-au-syd-containers-cloud-ibm-com:30433
  name: default/c100-e-au-syd-containers-cloud-ibm-com:30433/
current-context: default/c100-e-au-syd-containers-cloud-ibm-com:30433/
kind: Config
preferences: {}
users:
- name: /c100-e-au-syd-containers-cloud-ibm-com:30433
  user:
    token: ""
```

As a reference, here is the kubeconfig file set when the issue does NOT occur. Notice the user AND the token are set:
```
apiVersion: v1
clusters:
- cluster:
    server: https://c100-e.au-syd.containers.cloud.ibm.com:30433
  name: sm-zqe5to-testsm-gp-6-ocp/c3gj1v5s005sa12n1sm0
- cluster:
    server: https://c100-e.au-syd.containers.cloud.ibm.com:30433
  name: c100-e-au-syd-containers-cloud-ibm-com:30433
contexts:
- context:
    cluster: sm-zqe5to-testsm-gp-6-ocp/c3gj1v5s005sa12n1sm0
    namespace: default
    user: ""
  name: sm-zqe5to-testsm-gp-6-ocp/c3gj1v5s005sa12n1sm0
- context:
    cluster: c100-e-au-syd-containers-cloud-ibm-com:30433
    namespace: default
    user: IAM#goldeneye.development@ibm.com/c100-e-au-syd-containers-cloud-ibm-com:30433
  name: default/c100-e-au-syd-containers-cloud-ibm-com:30433/IAM#goldeneye.development@ibm.com
current-context: default/c100-e-au-syd-containers-cloud-ibm-com:30433/IAM#goldeneye.development@ibm.com
kind: Config
preferences: {}
users:
- name: IAM#goldeneye.development@ibm.com/c100-e-au-syd-containers-cloud-ibm-com:30433
  user:
    token: sha256~REMOVED
```

As a comparison, to make sure the issue is not related to the serviceId or the cluster itself, I tested going through the steps at https://cloud.ibm.com/docs/openshift?topic=openshift-access_cluster#access_automation on the same cluster. No issue, I can execute the commands against the cluster corresponding to the terraform module. Note that I had to specify a --server in the oc login command (documented as optional in the doc) otherwise I was getting a 500 response, so possibly the terraform provider may be bumping into the same issue - just some speculation.
