### ISSUE TITLE
Error while creating Virtual Server Instance using ibm_is_instance

### ISSUE THREAD

**Issue by kavitarane4783** [IBM-Cloud/terraform-provider-ibm#3443]
### Affected Resource(s)

* ibm_is_instance

### Ansible 

```
Ansible playbook task
    - name: Configure VSI
      ibm_is_instance:
        name: "{{ name_prefix }}-vsi"
        state: available
        id: "{{ vsi.id | default(omit) }}"
        vpc: "{{ vpc.id }}"
        profile: "{{ vsi_profile }}"
        image: "{{ image_dict[vsi_image] }}"
        keys:
          - "{{ ssh_key.id }}"
        primary_network_interface:
          - subnet: "{{ subnet.id }}"
        zone: "{{ zone }}"
      register: vsi_create_output

```

### Panic Output
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auto_delete_volume": null,
            "boot_volume": [
                {
                    "name": "ansible-test-boot-volume"
                }
            ],
            "dedicated_host": null,
            "dedicated_host_group": null,
            "force_recovery_time": null,
            "generation": 2,
            "ibmcloud_api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "id": null,
            "image": "r014-f46c15d1-3f78-4cbf-8f62-bdfa282cbc12",
            "keys": [
                "r014-e530733b-38d2-4c58-adba-1de7615a7078"
            ],
            "name": "ansible-test-vsi",
            "network_interfaces": null,
            "primary_network_interface": [
                {
                    "subnet": "0767-fa4a2ca8-0803-4d2b-90e1-4b3808cc1931"
                }
            ],
            "profile": "bx2-2x8",
            "region": "us-east",
            "resource_group": null,
            "state": "available",
            "tags": null,
            "user_data": null,
            "volumes": null,
            "vpc": "r014-7b19e988-c3c5-4ed4-b1f9-40e1a78863c9",
            "wait_before_delete": null,
            "zone": "us-east-2"
        }
    },
    "msg": "",
    "rc": 1,
    "resource": {
        "_name": "ansibletestvsi",
        "_type": "ibm_is_instance",
        "target": "ibm_is_instance.ansibletestvsi"
    },
    "stderr": "\nError: Boot volume capacity must be equal to image minimum volume size\n\n  on ibm_is_instance_ansibletestvsi.tf line 1, in resource \"ibm_is_instance\" \"ansibletestvsi\":\n   1: resource ibm_is_instance \"ansibletestvsi\" {\n\n\n",
    "stderr_lines": [
        "",
        "Error: Boot volume capacity must be equal to image minimum volume size",
        "",
        "  on ibm_is_instance_ansibletestvsi.tf line 1, in resource \"ibm_is_instance\" \"ansibletestvsi\":",
        "   1: resource ibm_is_instance \"ansibletestvsi\" {",
        "",
        ""
    ],
    "stdout": "ibm_is_instance.ansibletestvsi: Creating...\n\nWarning: Deprecated Attribute\n\nThe generation field is deprecated and will be removed after couple of\nreleases\n\n",
    "stdout_lines": [
        "ibm_is_instance.ansibletestvsi: Creating...",
        "",
        "Warning: Deprecated Attribute",
        "",
        "The generation field is deprecated and will be removed after couple of",
        "releases",
        ""
    ]
}

```

### Expected Behavior
Virtual Machine Instance should get created
### Actual Behavior

Throwing error for creating virtual instance in the ansible task
