### ISSUE TITLE
Satellite location name should be mutable 

### ISSUE THREAD

**Issue by simonnaegele** [IBM-Cloud/terraform-provider-ibm#5711]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**IBM satellite locations now support changing its name and description providing using a new graphql endpoint. Even though changing the name is not yet supported by the terraform-provider-ibm plugin it should still allow a change by the user using the new graphql endpoint.
Currently a "terraform destroy" is broken if the name was changed by the user. To fix it the terraform-provider-ibm plugin needs to remove the satellite location name from the list of immutable properties and in addition the location ID should be used when doing the destroy, because the name might have changed in the meantime.**

### Terraform CLI and Terraform IBM Provider Version

          name: github.com/IBM-Cloud/terraform-provider-ibm
          version: 1.68.1

### Affected Resource(s)

* ibm_satellite_location

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please share a link to the ZIP file.
```

### Debug Output

```        
        summary: '''location'' attribute is immutable and can''t be changed'
        severity: error
        resource: ibm_satellite_location
        operation: CustomizeDiff
        component:
          name: github.com/IBM-Cloud/terraform-provider-ibm
          version: 1.68.1
```

### Expected Behavior
Destroy of satellite location should succeed even if "location" attribute (name) was changed by the user

### Actual Behavior
Destroy of satellite location fails because "location" attribute (name) was changed by the user

### Steps to Reproduce

1. change satellite location name using new graphql endpoint
2. `terraform destroy` of this satellite location

### References

* #0000
