### ISSUE TITLE
ibm_container_cluster_config does not work of openshift clusters

### ISSUE THREAD

**Issue by hassenius** [IBM-Cloud/terraform-provider-ibm#656]
### Terraform Version
13:34 $ terraform version
Terraform v0.11.14
+ provider.ibm v0.17.1
+ provider.kubernetes v1.8.0

### Affected Resource(s)
ibm_container_cluster_config

### Terraform Configuration Files
```hcl
data "ibm_container_cluster_config" "refarch_ds_cluster" {
  cluster_name_id = "${ibm_container_cluster.iks_refarch_cluster.id}"
  resource_group_id = "${data.ibm_resource_group.refarch.id}"
  region          = "${var.iks_region}"
}
```

### Expected Behavior
ibm_container_cluster_config should have downloaded a config that could be used by the kubernetes provider

### Actual Behavior
ibm_container_cluster_config downloads a configuration without auth information, so can not be used by kubernetes provider
Here's an example of the file that is downloaded
```
cat ~/390bf48c704043cf964fb04bc9d271be_k8sconfig/config.yml 
apiVersion: v1
clusters:
- name: hktest
  cluster:
    server: https://c1-e.eu-gb.containers.cloud.ibm.com:23166
contexts:
- name: hktest
  context:
    cluster: hktest
    user: hans.moen@ie.ibm.com
    namespace: default
current-context: hktest
kind: Config
users:
- name: hans.moen@ie.ibm.com
  user:
    token: ""
```

### Steps to Reproduce
Provision a openshift iks cluster and attempt to download cluster config

**Comment by hkantare** [comment]
I see same when I download using  ibmcloud cli 
```
Harinis-MacBook-Pro:cluster-worker-pool-zone hkantare$ cat /Users/hkantare/.bluemix/plugins/container-service/clusters/openshift/kube-config-wdc04-openshift.yml
apiVersion: v1
clusters:
- name: openshift
  cluster:
    server: https://c2-e.us-east.containers.cloud.ibm.com:22821
contexts:
- name: openshift
  context:
    cluster: openshift
    user: hkantare@in.ibm.com
    namespace: default
current-context: openshift
kind: Config
users:
- name: hkantare@in.ibm.com
  user:
    token: ""
```
